/**
 * Loads auxiliary JS libraries and stylesheets besides the main WASM module.
 */

// @ts-ignore Generated by wasm-pack during build
import initWasm from "../pkg/index.js";
import "../styles/app.scss";

export default async function initAux(wasm: Response): Promise<void> {
  await initWasm({ module_or_path: wasm });
}
